name: bilpo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter_animated_splash: ^0.0.10
  animated_splash_screen: ^1.3.0
  flutter:
    sdk: flutter

dev_dependencies:       
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
 
flutter:
  assets:
   - assets/pic/
   
  uses-material-design: true

    

 
